on:
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1.120.0
        with:
          bundler-cache: true
          ruby-version: .ruby-version
      - run: bundle exec rake
